#配置資料庫
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

#配置靜態資源路徑
  resources:
    static-locations: classpath:/ #只要是static裡面的資源，要從根目錄(resources底下)開始找
